# Generated by Django 4.1.3 on 2023-01-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='standard',
            field=models.CharField(max_length=255),
        ),
    ]
