# Generated by Django 4.1.3 on 2023-01-03 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_student_standard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Position',
        ),
    ]
